### ISSUE TITLE
I have a question?

### ISSUE THREAD

**Issue by Abhinaba12** [tathagata1805/Video-Conference-App#1]
What is the ID to call? Where can I find it ?

**Comment by tathagata1805** [comment]
If you can be a bit more specific then it would be easier for me to help you. Else you can reach me out via mail at tathagata1805@gmail.com

**Comment by Abhinaba12** [comment]
![Screenshot 2024-08-02 at 12 22 41 AM](https://github.com/user-attachments/assets/2f982829-2fc5-47f5-b8c0-5f85fff5d539)
In this section i'm facing problem, what is the ID?

**Comment by tathagata1805** [comment]
When you enter your name and click on "Copy your ID" button, it automatically copies the ID, which you need to paste it on the other input. If you're just working on the same window paste that ID itself, it will be like calling yourself. If you've another window open, paste the ID there and copy that ID and paste it here, this should initiate the call.
This ID is basically where the socket connection happens.
Hope it helps.
Do let me know if you've anything else to share!
All the best!

**Comment by Abhinaba12** [comment]
Hey! Man I'm looking for Mern stack/Full stack/Software engineering role.

Can you help me out ?

Here is my resume
